### ISSUE TITLE
What kind of bullshit this project?

### ISSUE THREAD

**Issue by sensboston** [nathanchere/MatrixSaver#1]
Why do you call this, non-working bullshit project a "matrix screensaver"??? Did I missed something? This code do, actually, nothing, and far-far away from screensaver at all, not talking about "Matrix"...

**Comment by nathanchere** [comment]
My deepest and most humble apologies to you.

![image](https://user-images.githubusercontent.com/853261/72080056-607a5a00-32fc-11ea-821d-10206c3989f4.png)

I'm so inspired by your non-working bullshit web site that I'll fix my untouched-for-6-years-other-than-to-add-a-disclaimer-that-it-is-no-longer-maintained-and-does-not-work-out-of-the-box project just for you.

Anything else I can help you out with cockbreath?
